name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  Configuration: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1

    - run: dotnet --info

    - run: dotnet tool restore

    - name: Run nbgv
      run: dotnet nbgv get-version -p src

    - name: Restore
      run: dotnet restore src -v normal

    - name: Build
      run: dotnet build src -t:build,pack --no-restore -m  -bl:obj/logs/build-${{ matrix.os }}.binlog

    - name: Test
      run: dotnet test src --no-build

    - name: Upload nugets
      if: github.event_name == 'push' && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: nugets
        path: bin/Packages/${{ env.Configuration }}

    - name: Upload logs
      uses: actions/upload-artifact@v1
      with:
        name: logs-${{ matrix.os }}
        path: obj/logs/

    - name: Build samples
      shell: pwsh
      run: samples/build.ps1
    
    - name: Add Deploy Location
      if: matrix.os == 'windows-latest'
      # if: (github.event_name == 'push' && github.ref == 'master') || (github.event_name == 'release')
      run: dotnet nuget add source https://nuget.pkg.github.com/cythral/index.json -n github -u cythral -p "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Deploy
      if: matrix.os == 'windows-latest'
      run: dotnet nuget push bin/Packages/${{ env.Configuration }}/*.nupkg -s github
    
    


        
      
